name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:

  github:
    name: github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v6
        if: github.ref_type == 'tag'
        with:
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: "true"
