name: Tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    name: latest version tests (${{ matrix.os }}, ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-22.04
            compiler: g++
          - os: ubuntu-22.04
            compiler: clang++
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
          # Linux ARM
          - os: ubuntu-22.04-arm
            compiler: g++
          - os: ubuntu-22.04-arm
            compiler: clang++
          # macOS x86_64
          - os: macos-13
            compiler: clang++
          # macOS ARM
          - os: macos-latest
            compiler: clang++
          # Windows
          - os: windows-latest
            compiler: MSVC
            exe_suffix: .exe
          - os: windows-latest
            compiler: g++
            exe_suffix: .exe
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ clang cmake ninja-build
      - name: Build (non-MSVC)
        if: matrix.compiler != 'MSVC'
        shell: bash
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          cat build/CMakeCache.txt
          cmake --build build -j4
      - name: Build (MSVC)
        if: matrix.compiler == 'MSVC'
        run: |
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          cmake --build build --config Release -j4
      - name: Run tests
        run: |
          ls build
          ./build/sqd_tests${{ matrix.exe_suffix }}
      - name: Run benchmarks
        run: |
          ./build/sqd_benchmarks${{ matrix.exe_suffix }}
