name: Tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    name: latest version tests (${{ matrix.os }}, ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        fail-fast: false
        include:
          # Linux x86_64
          - os: ubuntu-22.04
            compiler: g++
          - os: ubuntu-22.04
            compiler: clang++
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
          # Linux ARM
          - os: ubuntu-22.04-arm
            compiler: g++
          - os: ubuntu-22.04-arm
            compiler: clang++
          # macOS x86_64
          - os: macos-13
            compiler: clang++
          # macOS ARM
          - os: macos-latest
            compiler: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ clang cmake ninja-build
      - name: Build
        shell: bash
        run: |
          cmake -S . -B build -G Ninja
          ninja -C build
      - name: Run tests
        shell: bash
        run: |
          ./build/sqd_tests
      - name: Run benchmarks
        shell: bash
        run: |
          ./build/sqd_benchmarks
